Issue 3: Implement JSON Import and Export Backup Functionality
GetAmbush/ambush-app pull request #83
Opened 2024-11-14 20:25 UTC by pnalvarez

# Description:
Thir PR implements a feature that allows exporting data from the application, which is saved in the browser preferences to a JSON file as a back up and importing again to recover the back up in case user loses data across eventual migrations or data cleaning(Safari for example).

# Implemented features

1. Export JSON back up to computer file system
2. Import JSON back up from file system
3. Format error handling
4. UI to recover back up from onboarding root screen and invoice list page, and download back up from invoice list page.

#How to test
1. Run the application 
2. Follow through the onboarding filling all required information
3. On invoice list page, after creating some new invoices, tap the download icon on top bar to download all data in a JSON file
4. Check JSON file is valid
5. Run application in another browser/port and at onboarding screen, click to `Retrieve from back up` and select the saved JSON file.
6. Check that all invoices are rendered to the list and verify all settings were correctly uploaded in their respective sections.
7. Change any configuration in the JSON file and from the invoice list page, upload the file again to check it was correctly saved.

#Edge cases
1. In onboarding screen, write a JSON file in a wrong format and try to upload to the application to receive an error dialog
2. Repeat previous step in invoice list page

2024-11-14 20:36 UTC, alexrodrigues commented
Hey @pnalvarez! Don't forget to link your issue... you should write something like "closes #{issue_number}"

2024-11-18 11:47 UTC, theolm requested changes
I didn't understood all the changes, but I left some minor comments.

The blocking here is the the wrong usage of the data source and the manual creation of json in each model. This should be the last resort as it would greatly impact the maintenance of the app. 

Please take a look in this lib. It seems to do what you need.
https://github.com/BinaryLurkerex/JSON-Hive-Generator

native platforms (Android, ios, macos,linux,widows) will require a different solution. You can address this solution in a subsequent PR.

2024-11-18 11:47 UTC, theolm commented on lib/src/data/datasource/local_datasource.dart
> +  Future<bool> retrieveBackup();
Those names are not very good.

by the naming IDK what the function does. `saveBackup` saves in the database? or it creates the backup for the user to download? 


Change it to:
Future<bool> createBackup();
 Future<bool> restoreBackup();

2024-11-18 11:47 UTC, theolm commented on lib/main.dart
> +    final IFileService fileService = FileService();
not used.

2024-11-18 11:47 UTC, theolm commented on lib/src/data/datasource/local_datasource.dart
> +    }
I think this logic doesn't belong in the data source.
Move it to the repository. 

This datasource only saves and get data from Hive.

2024-11-18 11:47 UTC, theolm commented on lib/src/data/datasource/local_datasource.dart
> +    }
same here.

2024-11-18 11:47 UTC, theolm commented on lib/src/data/datasource/local_datasource.dart
> +  }
Same here. Isolate this in a different class.

2024-11-18 11:47 UTC, theolm commented on lib/src/data/models/hive_bank_info.dart
> +      };
dumb question. can't you use the HiveField as a key?
I thought that Hive had something ready to use.

2024-11-18 11:47 UTC, theolm commented on lib/src/designsystem/error_dialog.dart
> +          ));
This dialog has fixed strings, so It can't be a part of the design system since it's not a modular component.

Add parameters to it: title, content and button text.

2024-11-18 11:47 UTC, theolm commented on lib/src/presentation/onboarding/onboarding_page.dart
> +                text: "Retrieve a back up",
"Restore a back up"

2024-11-20 14:15 UTC, theolm requested changes
This solution breaks the clean architecture.
The Domain layer (models in this case) should not have any dependencies. Here you are adding a dependency into an external package (json_annotation).

2024-11-20 15:26 UTC, closed without merging