Issue-81: Enhancements on the onboarding flow
GetAmbush/ambush-app pull request #84
Opened 2024-11-14 20:26 UTC by alexrodrigues

There were some minor adjustments to the onboarding flow and the success screen. This PR includes all these changes.

Android (Small Phone):

![android_small_3](https://github.com/user-attachments/assets/3ef4c172-9238-4b24-938f-30a15bfe9c3b)
![android_small_success](https://github.com/user-attachments/assets/5d035a78-836b-4491-ac36-0f995d55159e)
![android_small_4](https://github.com/user-attachments/assets/984f412c-4063-4be7-9bfb-cc2d67646508)
![android_small_1](https://github.com/user-attachments/assets/4e86e840-8515-419d-97ae-056dc41b9fc9)
![android_small_2](https://github.com/user-attachments/assets/6c410365-9894-43ca-8ddf-ad1478787ded)

iPad Success:

![Simulator Screenshot - iPad (10th generation) - 2024-11-14 at 12 25 34](https://github.com/user-attachments/assets/b9c076eb-015e-4cae-80c5-c37b0de30645)

iPhone Success: 

![Simulator Screenshot - iPhone 16 - 2024-11-14 at 12 33 28](https://github.com/user-attachments/assets/5feb20ee-0d7f-4100-9489-fb96362f9a84)

Happy Path:

https://github.com/user-attachments/assets/d8b410d7-28a7-455d-b2b5-f41dddf362e9

I will do this later:

https://github.com/user-attachments/assets/157500f1-b125-4a48-a69f-65f40a9d611c

Sad Path:

https://github.com/user-attachments/assets/77d7b2c1-38d1-423f-9b05-0f9c567fd26b

closes issue #81

2024-11-14 20:29 UTC, alexrodrigues commented on ios/Runner/AppDelegate.swift
> +@main
After Swift 5.3 we should use this annotation, this change will ensure compatibility with Swift UI 😄

2024-11-14 20:44 UTC, pnalvarez commented on lib/src/core/routes/app_route.dart
> +    AutoRoute(page: OnboardingSuccessRoute.page),
🔥

2024-11-14 20:45 UTC, pnalvarez commented on lib/src/presentation/settings/success/onboarding_success_screen.dart
> +class OnboardingSuccessScreen extends StatelessWidget {
Minor: I think the project is adopting `Page` for screen suffix as a pattern,

2024-11-14 20:47 UTC, pnalvarez commented on lib/src/presentation/settings/success/onboarding_success_screen.dart
> +            Navigator.pop(context);
Isn't the screen supposed to rely on its `flow navigator` to pop the context? I think we only call the `Navigator` for alert dialogs.

2024-11-15 15:14 UTC, theolm reviewed
Nice Pr.
I would suggest to also address the maxWidth of the main content.
I would create a custom scaffold for the screens to use, This way it will be easier to maintain.

2024-11-15 15:14 UTC, theolm commented on lib/src/presentation/settings/success/onboarding_success_screen.dart
> +                    width: 16.0,
Check the file lib/src/core/settings/const.dart

2024-11-18 13:52 UTC, alexrodrigues commented on lib/src/presentation/settings/success/onboarding_success_screen.dart
> +class OnboardingSuccessScreen extends StatelessWidget {
Fixed!!

2024-11-18 13:52 UTC, alexrodrigues commented on lib/src/presentation/settings/success/onboarding_success_screen.dart
> +            Navigator.pop(context);
Fixed!!

2024-11-18 14:26 UTC, alexrodrigues commented on lib/src/presentation/settings/success/onboarding_success_screen.dart
> +                    width: 16.0,
Hey Theo, I really appreciate your feedback! Could you please help me understand the "custom scaffold" part?
By the way, I added the margins from the const.dart file and also included the maxWidth constraints

2024-11-18 15:34 UTC, theolm commented on lib/src/presentation/settings/success/onboarding_success_screen.dart
> +                    width: 16.0,
Your solution of maxWidth only works for the OnboardingSuccessPage. Every other page will not have a good experience in wide screens.

I'm suggesting you to create a custom component based on the scaffold (e.g. ConstrainedScaffold) that accepts a max width as a parameter. This way you can replace the current scaffold for the ConstrainedScaffold and fix all the screens at once.

2024-11-18 15:48 UTC, alexrodrigues commented on lib/src/presentation/settings/success/onboarding_success_screen.dart
> +                    width: 16.0,
Got it! Thanks for the explanation, I will work on that!

2024-11-18 19:55 UTC, alexrodrigues commented on lib/src/presentation/settings/success/onboarding_success_screen.dart
> +                    width: 16.0,
I’ve just created the ConstrainedScaffold and replaced it in each Scaffold across the Ambush App! Please let me know if this commit makes sense `https://github.com/GetAmbush/ambush-app/pull/84/commits/b632169263193914a65a3101df2e2119d732992e`

2024-11-19 18:50 UTC, theolm requested changes
The component is missing some attributes and the pages still have different behaviour.

The new screen has a constrained size while the others have an infinity width.

2024-11-19 18:50 UTC, theolm commented on lib/src/designsystem/constrained_scaffold.dart
> +}
I'm afraid that's not right. This custom component must not remove the capabilities of its parent. The scaffold accepts multiple parameters to customize its behaviour. The custom scaffold must accept the same parameters.

scafold params
```dart
super.key,
    this.appBar,
    this.body,
    this.floatingActionButton,
    this.floatingActionButtonLocation,
    this.floatingActionButtonAnimator,
    this.persistentFooterButtons,
    this.persistentFooterAlignment = AlignmentDirectional.centerEnd,
    this.drawer,
    this.onDrawerChanged,
    this.endDrawer,
    this.onEndDrawerChanged,
    this.bottomNavigationBar,
    this.bottomSheet,
    this.backgroundColor,
    this.resizeToAvoidBottomInset,
    this.primary = true,
    this.drawerDragStartBehavior = DragStartBehavior.start,
    this.extendBody = false,
    this.extendBodyBehindAppBar = false,
    this.drawerScrimColor,
    this.drawerEdgeDragWidth,
    this.drawerEnableOpenDragGesture = true,
    this.endDrawerEnableOpenDragGesture = true,
    this.restorationId,
```

2024-11-19 18:50 UTC, theolm commented on lib/src/presentation/settings/base_settings_page.dart
> +      maxWidth: double.infinity,
The `maxWidth` is probably not infinity. I think it should be defaultPageMaxWidth.

2024-11-19 18:50 UTC, theolm commented on lib/src/designsystem/constrained_scaffold.dart
> +    required this.body,
Follow the same pattern as the Scaffold. I think this should not be required.

btw. the default maxWidth should be infinity.

2024-11-19 18:50 UTC, theolm commented on lib/src/presentation/settings/success/onboarding_success_screen.dart
> +import '../../../designsystem/constrained_scaffold.dart';
Don't use the relative path in the import unless is an autogenerated file.

2024-11-19 19:34 UTC, alexrodrigues commented on lib/src/designsystem/constrained_scaffold.dart
> +}
Got it! I've circled back and included all the default Scaffold into the ConstrainedScaffold component.
This way the Engineer can customize the Constrained Scaffold the way he wants

[commit](https://github.com/GetAmbush/ambush-app/pull/84/commits/29ef607a3994a14a6fd3b508094fd4b45c3a55e4#diff-b2e72983761ea3c5392158ce2a1180a63e1c272f50c83c24ff1ff857f48972ed)

2024-11-19 19:36 UTC, alexrodrigues commented on lib/src/presentation/settings/base_settings_page.dart
> +      maxWidth: double.infinity,
My mistake, I’ve gone back and changed it to use defaultPageMaxWidth

[Commit](https://github.com/GetAmbush/ambush-app/pull/84/commits/29ef607a3994a14a6fd3b508094fd4b45c3a55e4)

2024-11-19 19:49 UTC, alexrodrigues commented on lib/src/designsystem/constrained_scaffold.dart
> +    required this.body,
Agreed! I've just implemented your suggestions:

```
  const ConstrainedScaffold({
    super.key,
    this.appBar,
    this.maxWidth = double.infinity,
```

[Commit](https://github.com/GetAmbush/ambush-app/pull/84/commits/862c5b98b99ae91fb9b2eba19fa59fb20cbd558e)

2024-11-19 19:49 UTC, alexrodrigues commented on lib/src/presentation/settings/success/onboarding_success_screen.dart
> +import '../../../designsystem/constrained_scaffold.dart';
Good to know! I've just fixed that too

[Commit](https://github.com/GetAmbush/ambush-app/pull/84/commits/862c5b98b99ae91fb9b2eba19fa59fb20cbd558e)

2024-11-19 19:50 UTC, alexrodrigues commented
Thanks for your feedback @theolm!

2024-11-20 14:07 UTC, theolm approved these changes
Nice job!

2024-11-20 14:08 UTC, merged